cncf/tag-security

- README.md
adding self to help review doc
> Kamil add branch

- README.md
Signed-off-by: Doug Davis <dug@us.ibm.com>
> Add myself to the list of members

- README.md
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> Add Justin Cormack to participants

- README.md
Added myself to the list of members.
> Add Cheney Hester to Member List

- README.md
> fix @rcolline github name

- README.md
Now working with single note taking document.
> Added links to 2018-08-02 and 2018-08-03 meetings

- README.md
This PR adds @rachelmyers to the list of members in the README.
> Add @rachelmyers to member list

- README.md
Would love to contribute and participate! Predominately focused on risk management and continuous compliance. For some context -> https://blog.docker.com/2018/05/automating-compliance-docker-ee-oscal/
> Interested new member

- README.md
I'm interested in contributing to the SAFE WG, assuming that it is still
open for additions. This PR adds  my name to the members list accordingly.
Signed-off-by: Evan Gilman <evan@scytale.io>
> Propose Evan Gilman as SAFE member

- policy-wg-merging.md
Added text to top to clarify that this proposal was accepted and we moved forward!
> note when policy WG merged

- README.md
I want to join in this group, please accept it :) Thanks
> Add myself into this group

- README.md
Greetings, I would like to be added as a member to this group to participate.
Me: https://www.cncf.io/persons/chase-pettet/
> Add member Chase Pettet (Wikimedia Foundation)

- wg.yaml
When we had originally pencilled this out at the beginning of year, we had JJ as Tech Lead to cover all the role. JJ is now a chair.
> JJ is a chair on Governance

- README.md
Changed to to "which".
Using in KubeCon Shanghai intro presentation:
https://docs.google.com/presentation/d/1U6KlwOO9lulBrenvVSXr3YX_gGio7NAqo_UJpugFb1Y/edit#slide=id.g4054009e6b_14_9
> Turned into a single sentence

- safe_usecases.md
I think we should add a use case about meeting compliance requirements
> Add use case for meeting compliance requirements

- README.md
> Sabree Blackmon information change

- README.md
added KubeCon/CloudNativeCon 2019 conferences
> add upcoming conferences

- README.md
This patch adds Justin Cappos and Santiago Torres-Arias to the members list.
> README: + Justin Cappos and Santiago Torres-Arias

- README.md
Added Brandon Lum to member list.
> README.md: +Brandon Lum

- README.md
> Add Ash Narkar to SAFE WG.

- README.md
- governance/process.md
addressed only the name of the group/repo
Note: there'll need to be additional edits to include reference to TOC, adjustments to process, etc.
> light edits for repo rename

- governance/process.md
bullets needed to be indented one space more for numbering continuity
> formatting of process doc for numbering continuity

- README.md
> Updated meeting information

- README.md
> Added DockerCon US 2019 in-person meetup

- README.md
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> Update the mailing list address

- README.md
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> Add Lorenzo Fontana to group members

- past-events.md
> Add slides for Protecting the Data Lake with OPA talk.

- past-events.md
Proposing #175 changes as a single PR.
> Update: Links for KubeCon EU 2019 talks

- README.md
Signed-off-by: danmx <daniel@iziourov.info>
> Adding new member

- README.md
Adding myself - Leonardo Di Donato - as a member.
> New membership (myself)

- past-events.md
Update the current list to add video links to the recording on YouTube.
Add two other relevant talks:
- Securing Kubernetes with Trusted Platform Module
- Uber x Security: Why and How We Built Our Workload Identity Platform
> More past events updates from KubeCon Europe '19

- README.md
Adding simar7 to the members list
> Add Simar to members list in README.md

- README.md
> Add Roger Klorese (qnetter) to members

- README.md
Hello! I'd like to add myself to the members after attending some meetings. Thanks!
> Add Craig Ingram to members

- CONTRIBUTING.md
notices some points which were missing from style guide while reviewing https://github.com/cncf/sig-security/pull/207
> note about line wrapping and paragraph style

- roadmap.md
- removed comments column, only used for some items 
- reverse chronological order
> reverse order, adjust words

- roadmap.md
Adding task completions that are milestones. Team, please add to this list as we complete things!
> Adding task completion that are milestones

- landscape/README.md
refer to whitepaper issue #138
> add step of reviewing / revising categories

- README.md
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
> Add CNCF SIG Security Logo to README

- assessments/assessment-matrix.md
> draft overview matrix of projects and people

- README.md
Add Carlos Villavicencio Sanchez to member list.
> Add Carlos Villavicencio Sanchez to member list.

- README.md
I've been attending meetings for the last month or so.
> Adding Gareth Rushgrove as a member

- .github/settings.yml
- governance/roles.md
Adding role for meeting facilitator
starting with co-chairs as meeting facilitators
(also fixed capitalization consistency)
> propose meeting facilitator role

- .github/settings.yml
Add Brandon as meeting facilitator
> Add Brandon as meeting facilitator

- NEWMEMBERS.md
For issue https://github.com/cncf/sig-security/issues/226
> New members page 

- README.md
@dshaw 1 year @ultrasaurus @pragashj 2 years
Fixes #251.
> Add SIG-Security Chair terms

- README.md
Added quick links to README.md and caps consistency
> Added quick links to README.md and caps cons.

- .github/ISSUE_TEMPLATE/presentation.md
Addresses https://github.com/cncf/sig-security/issues/264
> Fix presentation template

- governance/roles.md
improve language on member roles and responsibility
addresses issue https://github.com/cncf/sig-security/issues/233
> governance: member roles and responsibility (#233)

- .github/ISSUE_TEMPLATE/security-assessment.md
since this ends up as an issue, as written relative link didn't work
I think absolute reference is a bit clearer, and consistent with other link
> fix link to be absolute

- usecases.md
> Update use cases

- README.md
correction noted at weekly wider SIG meeting
cc @ericavonb @hannibalhuang
> Policy team meeting => 3p Pacific

- assessments/projects/spiffe-spire/outline.md
made small edits to outline.md to include spelling correction, rephrasing, link to SPIFFE API doc
> rephrase, small corrections

- README.md
> add myself to member list

- CODEOWNERS
> Add chairs to assessment directory CODEOWNERS

- .github/ISSUE_TEMPLATE/security-assessment.md
- assessments/guide/README.md
- assessments/guide/security-reviewer.md
> Move assessment merge requirement

- assessments/projects/harbor/self-assessment.md
correcting the list of security reviewers and observers
Signed-off-by: Michael Michael <michmike@cs.stanford.edu>
> correcting an ommission

- CODEOWNERS
Update CODEOWNERS for TLs to handle new member requests as well.
> Update CODEOWNERS for README.md

- assessments/projects/spiffe-spire/self-assessment.md
Thanks @stefanberger for pointing out the typo
> Correct typo in SPIFFE/SPIRE assessment

- README.md
Unfortunately I have not been able to dedicate more time to the SIG, so removing myself from membership. Thank you all for all your continued work!
> Remove Craig

- README.md
due to COVID we are increasing chair term +3 months -- thank you @dshaw for your continued service!
> extend dshaw term

- governance/roles.md
> Roles - added Meeting Scribe(s) section

- README.md
> Add myself to list of new SIG members

- governance/cncf-projects.md
It looks like these became CNCF projects since original charter was written
> Add in-toto and harbor

- README.md
Please add me to the members list. 
Thanks!
> Adding Vinay to the Sig-Security WG members list

- README.md
Congrats Emily! Updating Emily as co-chair. 
https://lists.cncf.io/g/cncf-toc/topic/result_emily_fox_approved/77175814
> Updating Emily as co-chair. 

- assessments/projects/spiffe-spire/self-assessment.md
Should the year be 2020 instead of 2019?
> Updating to reflect the correct year when this assessment was conducted.

- README.md
Signed-off-by: Gadi Naor <gadi@alcide.io>
> Add sig member - Gadi Naor

- assessments/projects/keycloak/README.md
> assessments: Final Recommendation for the Keycloak security assessment.

- CONTRIBUTING.md
I thought we had these written down, but couldn't find them when commenting on https://github.com/cncf/sig-security/pull/452
Attempted to capture what is common practice across the repo -- we're not 100% consistent, but close
> file and directory naming conventions

- README.md
Signed-off-by: danpopsd dan.papandrea@sysdig.com
> add POP to members list

- README.md
Add Diego Comas to members list
> Add Diego Comas to members list

- supply-chain-security/compromises/2020/sonarqube.md
- supply-chain-security/compromises/README.md
Add reference to SUNSPOT - https://www.crowdstrike.com/blog/sunspot-malware-technical-analysis/
Fixed naming convention for type of compromise.
Slack discussion: https://cloud-native.slack.com/archives/CDJ7MLT8S/p1610478830312800
> Update SUNBURST/Solarigate compromise - Add CrowdStrike reference

- CODEOWNERS
- README.md
per https://lists.cncf.io/g/cncf-toc/message/5599
> updated with new TL's and added @Santiago-Torres as owner for supply 

- governance/roles.md
project Leads may be OWNERS of project directory in repo, Scribe not a requirement for project lead
> made @ultrasaurus suggestions to coincide with PR 506 

- supply-chain-security/compromises/2020/solarwinds.md
- supply-chain-security/compromises/README.md
Update the SUNBURST/Solarigate compromise base on the details from the
CrowdStrike blog on compromsing the publishing infrastructure with SUNSPOT
Signed-off-by: Joshua Lock <jlock@vmware.com>
> Update SUNBURST/Solarigate compromise

- supply-chain-security/compromises/compromise-definitions.md
> Add "malicious maintainer" to the compromise definitions

- supply-chain-security/compromises/2018/event_stream.md
- supply-chain-security/compromises/README.md
> Document the "event-stream" npm package exploit

- supply-chain-security/compromises/2020/thegreatsuspender.md
I have been more descriptive for
thegreatsuspender because I didn't find one good article
summarizing the exact details of the exploit.
Also, I wanted to bring attention to multiple red flags.
> Exploits catalog: Document thegreatsuspender saga

- supply-chain-security/compromises/2021/vscode.md
- supply-chain-security/compromises/README.md
Reference: https://www.bleepingcomputer.com/news/security/heres-how-a-researcher-broke-into-microsoft-vs-codes-github/
> Add VSCode GitHub vulnerability to the list Supply Chain Compromises

- .github/settings.yml
this was apparently not updated a while back, we'll see if we can use settings instead of Admin UI
> Update permission for chairs & TLs

- assessments/guide/self-assessment.md
* Wrapped lines in md table aren't rendering right
* Added link to CII as that might not be a widely used acronym
> self-assessment format tweak, added link to CII

- README.md
Adding Frederick to the list of members.
> Add Frederick to the list of members

- README.md
Adding Brad McCoy to the list of Members in the README.md file
> Add Brad McCoy to the list of members

- supply-chain-security/compromises/2018/event_stream.md
> docs: typo fixes

- roadmap.md
update some of the history for https://github.com/cncf/sig-security/issues/414
> adding some history

- README.md
adding Andreas Spanner to the member list
> adding Andreas Spanner to the member list

- README.md
> updating employer for myself

- README.md
It seems to assign ticket #496 to myself I need to be a contributor to the project. Maybe this is a good time to update the readme.md.
> Update readme.md with a new member Eli Nesterov

- assessments/README.md
- assessments/guide/README.md
- assessments/guide/joint-review.md
- assessments/intake-process.md
Found one or two broken links when discussing assessments with people, ran a link checker to find/clean up some more...
> Fixing various links in markdown docs

- .github/ISSUE_TEMPLATE/presentation.md
Include guidelines for presentation in template
> Include guidelines for presentation in template

- .github/ISSUE_TEMPLATE/joint-review.md
- .github/ISSUE_TEMPLATE/presentation.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/suggestion.md
Add "triage-required" label for every new issue
> Add triage-required label for new issues

- assessments/guide/README.md
- assessments/guide/security-reviewer.md
- assessments/projects/in-toto/self-assessment.md
- assessments/projects/spiffe-spire/self-assessment.md
- policy/overview-policy-formal-verification.md
Partial fix for issue: https://github.com/cncf/sig-security/issues/478
This is my first attempt at a PR for this topic, so happy to receive any feedback where I can learn
> Replaces his / her with their, she / he with they.

- README.md
Made corrections throughout README
* updated zoom link
* changed SIG-Security to STAG
* other changes based on recent process updates (assessment --> review)
> What: Updated STAG from SIG and corrected Zoom link

- .github/ISSUE_TEMPLATE/presentation.md
- governance/presentations.md
> Change presentation guidelines to explicit declaration

- .github/settings.yml
> .github: Add TLs/Chairs to the Meeting Facilitators list

- content/audit-log-analysis.md
- content/compliance.md
- content/index
- content/industries.md
- content/regulatory-audit.md
- content/resource-requests-and-limits.md
> content: Add content for compliance and runtime sections

- NEWMEMBERS.md
in relation to https://github.com/cncf/tag-security/issues/613
> SIG => TAG NEWMEMBERS.md

- README.md
> Fixing some formatting issues on the TL list

- governance/chair-proposal-process.md
> fixes for SIG to TAG rename

- .github/ISSUE_TEMPLATE/joint-review.md
- .github/ISSUE_TEMPLATE/presentation.md
- CODE-OF-CONDUCT.md
- CODEOWNERS
- README.md
- assessments/guide/README.md
- assessments/guide/joint-readme-template.md
- governance/presentations.md
- roadmap.md
- security-whitepaper/README.md
- security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
- supply-chain-security/supply-chain-security-paper/README.md
- supply-chain-security/supply-chain-security-paper/sscsp.md
- I switched the git links to the new default branch "main"
- If the link also pointed to sig-security I switched it to tag-security
> switch links to main branch

- .github/ISSUE_TEMPLATE/joint-review.md
> Fix security review instructions have bad link (404)

- security-whitepaper/cloud-native-security-whitepaper-simplified-chinese.md
> Fix incorrect link (404) in whitepaper

- README.md
Removes the reference to policy team lead and leaves it TBD
Fixes #659
> Policy team leads made TBD

- README.md
Contributions thus far:
- Reviewed SSCP paper
- Attended TAG meeting at the end of May
- Co-leading #635
Excited to learn and hopefully help more :D
> Submitting new member PR

- README.md
Contributions:
https://github.com/cncf/tag-security/pull/640
https://github.com/cncf/tag-security/pull/657
> Adding myself to the CNCF-Tag-Security Membership

- governance/roles.md
Add Chair Emeritus role to governance
> Add Chair Emeritus role to governance

- README.md
> Update chair roles in readme

- .github/settings.yml
Update settings.yml for chair transition
> Update settings.yml for chair transition

- past-events.md
> housekeeping past-events.md

- README.md
Fix all lint errors in `README.md`
> Fix lint for README.md

- governance/chair-transition.md
Why:
* Address issue #684 in order to provide continuity and consistency
* Documenting the checklist created from issue #684 for reuse.
> What: Create Chair Transition checklist

- CONTRIBUTING.md
want to make sure this passes the linter before I do content edits!
pre-condition for: https://github.com/cncf/tag-security/issues/613
> word wrap, formatting, spelling and broken links

- README.md
An attempt to make the phone numbers easier to parse.
+ fixes the zoom meeting link formatting.
> README: improvements to Zoom meeting section

- project-resources/README.md
- project-resources/templates/ISSUE_TEMPLATE.md
- project-resources/templates/SECURITY.md
- project-resources/templates/SECURITY_CONTACTS.md
- project-resources/templates/embargo-policy.md
- project-resources/templates/embargo.md
- project-resources/templates/incident-response.md
Why:
* contributor strategy uses `` to indicate action
* inserting  where the project is required to make changes.
> What: Updating project resource to match contributor strategy format

- ci/spelling-config.json
- security-whitepaper/README.md
> Add retrospective section to Whitepaper README.md

- README.md
Adding Ashish as a new CNCF Member
> Updated ReadME to add a new CNCF Member

- README.md
Add Sayantani as a new CNCF member
> Readme updated to add new CNCF member

- content/container-application-manifest.md
- content/security-checks-in-development.md
- content/security-policies.md
- content/zero-trust-architecture.md
Signed-off-by: Jim Bugwadia <jim@nirmata.com>
add Kyverno for config scanning and CI/CD checks
> add Kyverno

- content/service-mesh.md
Adds Open Service Mesh, updates Service Mesh Interface and removes Trivy (as it is no Service Mesh).
> Update CNSMap Service Meshes

- content/container-application-manifest.md
> add-terrascan-under-containe-application-manifest

- content/static-analysis-and-security-testing.md
> updated-IAC-static-analysis- security-testing

- README.md
- explain group's raison d'être
- link to further details page
- provide meeting time and how to join
> Add supply chain working group

- README.md
Hello,
I wanna be a member of Security TAG, actually I'm finding some tasks that I can contribute :)
> Add Mayo to STAG members

- components/sidenav.js
Justin Dorfman pointed out that the link is pointing to an old repo. Updating it.
> Update github repo link in sidebar

- README.md
Adding myself to the member list in `README`. I am new to TAG, and work for Prodigy Education in a devsecops role.
> feat: adding myself to the member list

- README.md
Update affiliation "TBD" for the time being
> Update @lumjjb affiliation

- supply-chain-security/compromises/README.md
Just a few formatting fixes
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Formatting fixes

- .github/settings.yml
- README.md
Why:
* [Elected to TOC](https://lists.cncf.io/g/cncf-toc/message/6557)
* reducing/altering permissions & updating chair status.
> What: Modify CODEOWNERS and README per #857

- ci/spelling-config.json
- security-whitepaper/secure-defaults-cloud-native-8.md
Fixes #734 
Related to #832 
Only spelling failures are for people names.
> Add Secure Defaults: Cloud Native 8

- supply-chain-security/compromises/2021/log4j.md
- supply-chain-security/compromises/2022/golang-buildpacks-compiler.md
- supply-chain-security/compromises/2022/js-faker-colors.md
- supply-chain-security/compromises/2022/wp-apthemes.md
- supply-chain-security/compromises/README.md
Input welcome on a few references to recent cases. I also reviewed the snap CVEs but as far as I could read they weren't about snaps themselves breaking confinement but about users getting root via abusing the snap architecture.
> compromises: log4j, js-faker-colors, golang-buildpacks, wp-apthemes

- .github/settings.yml
https://github.com/cncf/tag-security/issues/879
> Add chair sublimino

- README.md
https://lists.cncf.io/g/cncf-toc/message/6784
> Add @sublimino as co-chair

- security-whitepaper/v1/cloud-native-security-whitepaper-brazilian-portugese.md
Addresses https://github.com/cncf/tag-security/issues/509
Co-authored-by: Bruno Coelho <KoelhoSec@users.noreply.github.com>
> Add brazilian-portugese whitepaper translation

- security-whitepaper/v1/cloud-native-security-whitepaper-brazilian-portugese.md
Slowly trying to address the issues on PT-BR white-paper version from CI:
https://github.com/cncf/tag-security/runs/6508469351?check_suite_focus=true
> Fix CI issues for Brazilian Portuguese white-paper

- assessments/guide/README.md
> Fix tracking Issue link

- CODEOWNERS
Adds @mnm678 @mlieberman85 @ragashreeshekar to codeowners
> Update codeowners to include @mnm678 @mlieberman85 @ragashreeshekar

- supply-chain-security/compromises/2022/js-faker-colors.md
Adding another reference article with regards to the Colors and Faker npm modules incident
> docs: adding reference article

- supply-chain-security/supply-chain-security-paper/sscsp.md
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
cc: @PushkarJ 🙋🏻‍♂️
> docs(sscp): fix bold styles

- policy/overview-policy-build-time-dependency-vulns.md
Any and all feedback is welcome :)
Related to #855
> Add policy for build-time dependency vulns

- .github/settings.yml
> Add new TLs with permissions

- README.md
https://lists.cncf.io/g/cncf-toc/message/7086
> Add new TLs

- supply-chain-security/compromises/2022/php-pear-compromise.md
> docs: add the PHP PEAR package manager incident

- security-whitepaper/v2/cloud-native-security-whitepaper.md
Format Security Whitepaper 'Secrets Encryption' section (https://github.com/cncf/tag-security/issues/938)
> Format Security Whitepaper 'Secrets Encryption' section

- CODEOWNERS
> Update CODEOWNERS with Andy (co-chair)

- supply-chain-security/compromises/2022/pypi-malicious-packages.md
> docs: add pypi malicious packages incident

- ci/spelling.sh
to make the CI helpful and allow folks to easily and quickly fix their spellings I enabled the --show-suggestions CLI option
> build: show suggestions

- supply-chain-security/compromises/README.md
> docs: update table of contents with new PHP Pear incident

- security-whitepaper/v2/cloud-native-security-whitepaper.md
Removed duplicate period after the word "detection" under the "Finance" subsection
Signed-off-by: D-Squared70 <48914889+D-Squared70@users.noreply.github.com>
> Removed duplicate period

- README.md
Addresses https://github.com/cncf/tag-security/issues/818
> Update README with TAG Security calendar

- governance/github.md
Unblocks https://github.com/cncf/tag-security/pull/861
> Fix lint errors

- governance/github.md
> PR guidance: Fork or delete branches after merge

- README.md
- ci/spelling-config.json
> Add EMEA meeting time

- ci/spelling-config.json
- supply-chain-security/README.md
- supply-chain-security/supply-chain-security-paper/README.md
> Fix lints and spellchecks

- .github/auto_request_review.yml
> chore: add lirantal as reviewier for supply chain security section

- README.md
Signed-off-by: Matthew Giassa <matthew@giassa.net>
> Adding self (mgiassa) to contributors.

- ci/spelling-config.json
- supply-chain-security/compromises/2022/Comm100-live-chat-trojan.md
- supply-chain-security/compromises/2022/dropbox-github-account-breach.md
- supply-chain-security/compromises/2022/intel-alder-lake-BIOS-leak.md
- supply-chain-security/compromises/README.md
Credit to @Caze121 in https://github.com/cncf/tag-security/pull/993
> Add intel Alder Lake BIOS leak to compromises

- README.md
This changes the EMEA meeting timezone from BST to UTC
Signed-off-by: Rory McCune <raesene@gmail.com>
> Change EMEA meeting timezone

- supply-chain-security/compromises/2022/docker-hub-malicious-containers.md
- supply-chain-security/compromises/README.md
Signed-off-by: Ryan Gibbons <ryanjgibbons@hotmail.com>
> Adding docker hub malicious container findings

- PUBLICATIONS.md
- README.md
- ci/spelling-config.json
> Add list of publications

- PUBLICATIONS.md
I realized I forgot to add this item to the PUBLICATIONS.md file.
> Add Catalog of Supply Chain Compromises to Publications.md

- assessments/guide/README.md
- assessments/guide/joint-review.md
- ci/links.sh
- ci/lint.sh
- ci/spelling-config.json
- governance/communications/README.md
- security-whitepaper/v1/cloud-native-security-whitepaper.md
- security-whitepaper/v2/cloud-native-security-whitepaper.md
Fixes a few minor grammar errors that I found while recording for the audio version.
I also added a comment to the lint and links GH action files to describe how to run the processes manually on the whole repository (not just changed files). I then went ahead and fixed a few of those issues.
> CNSWP grammar fixes

- .github/settings.yml
> Add @jkjell to permissions for leading ssc policy (#987)

- .github/settings.yml
Fixes #994 
Signed-off-by: Pushkar Joglekar <3390906+PushkarJ@users.noreply.github.com>
> Add `lirantal` to collaborator with "Read" access

- security-whitepaper/v2/cloud-native-security-whitepaper.md
- Delete unnecessary text
- Fix unexpected nested list by newlines
> Fix some format

- assessments/projects/pixie/README.md
- assessments/projects/pixie/self-assessment.md
Checking in the self-assessment for https://github.com/cncf/tag-security/issues/1068. 
Thanks all for the review and great feedback during this process!
cc: @JustinCappos
> Add Pixie Self-Assessment

- assessments/guide/self-assessment.md
This change was requested by @JustinCappos following his review of LFEL1005
> Added express learning course link to self-assessments.md

- .github/ISSUE_TEMPLATE/unconference.md
Add a template for coordinating unconference talks at the Security Hub!
> Add unconference template

- README.md
https://lists.cncf.io/g/cncf-toc/message/8317
> Chair transition Aradhna -> Marina

- website/content/_index.md
Initiating a streamlined update with this PR to update the incorrect info over duplicating the entire README. This initial pass introduces necessary revisions on links and resources, meeting details, and leadership roster. Further review and collaborative refinement are welcome to ensure accuracy and coherence.
> Streamlined update to TAG Security website info

- website/config.toml
- website/layouts/_default/content.html
- website/layouts/partials/feedback.html
> Add feedback buttons to pages

- README.md
Stepping down from my position as one of the designated facilitator for the TAG security assessments after evaluating my current commitments and responsibilities, both professionally and personally.
The process is currently very effective with the time and energy that Justin dedicates to it, and I'm eager to see how the TAG security assessments continue to grow and evolve.
I look forward to continuing to contribute to the TAG in the capacity of TL.
> change from facilitators to facilitator for security assessments

- assessments/projects/flatcar/self-assessment.md
Added Flatcar Project Security Self-Assessment.
Please feel free to share your feedback on the security self-assessment.
> Flatcar Project Security Self-Assessment

- website/layouts/_default/baseof.html
- website/layouts/partials/under-construction-tmp.html
Part of #1257 
[[Preview](https://deploy-preview-1258--tag-security.netlify.app)]
> Added construction banner

- .github/auto_request_review.yml
- README.md
Part of #1250 
ref:
https://lists.cncf.io/g/cncf-toc/topic/tag_security_co_chair/105544165
https://lists.cncf.io/g/cncf-toc/topic/announcement_tag_security/105941090
> Onboarding @eddie-knight as co-chair

- README.md
- community/automated-governance/README.md
- community/catalog/README.md
- community/compliance/README.md
- community/controls/README.md
- community/research/README.md
- community/supply-chain-security/README.md
This pull request updates the README to include information about the Security TAG's working groups and community meetings. It details how the working groups organize community activity, their focus areas, and the responsibilities of the working group leads. Additionally, it clarifies the types of deliverables produced by the working groups and where to find them in the repository.
This update also creates a directory structure for each working group and their project files, improving organization and accessibility to these different resources.
Closed #1266.
> Update README with Working Groups and Community Directory

- website/content/blog/website-relaunch-2024.md
This fixes the issue with this blog post not appearing.
> removed linter line from blog post

- README.md
Updates NA meeting link to https://zoom-lfx.platform.linuxfoundation.org/meeting/92340369657?password=76e24ffd-69f2-41a8-8aed-13796805225d
> Update README to updated meeting link on LFX platform

- README.md
> Adds APAC timezone meeting details to README

- community/assessments/projects/wasmcloud/self-assessment.md
Adds the completed TAG Security self-assessment. Please let me know if we missed anything important!
> feat(assessments): Adds wasmCloud project self-assessment

- community/working-groups/commons/README.md
- community/working-groups/cross-foundation-alignment/README.md
Belated charter for #1313
During the course of drafting this with @mnm678, we considered that a different name may better encapsulate the goals of the WG.
cc/ @mlieberman85
> Added charter for Cross-Foundation Alignment WG (previously Baseline)

- community/events/cloud-native-security.md
> Update and rename cloud_native_security.md to cloud-native-security.md

- community/working-groups/compliance/README.md
> fix: correct meeting link in README.md

- community/assessments/projects/lima/self-assessment.md
I'm not sure what is the criteria to be marked as "Complete".
Please let me know if I'm still missing something
> lima/self-assessment.md: mark as Complete

- community/resources/README.md
This PR creates the resources landing page, found at the https://tag-security.cncf.io/community/resources/ path.
The page contains information about all the documents within it, making it easier for users to find themslves in the website.
> Creating the /resources landing page.

- README.md
v2 is now available!
(This follows up on #1461)
> Update the Supply Chain Best Practices whitepaper link

- CONTRIBUTING.md
> Fix TAG Security charter link in Contributing

- website/content/blog/kubecon-na-2025.md
Minor update to the blog post to force a redeployment :smile:
> docs: update authors in kubecon-na-2025.md

- community/resources/security-lexicon/cloud-native-security-lexicon.md
This PR adds the definition for Automated Governance to the Cloud Native Security Lexicon for review and discussion.
Relevent discussion on this addition can be found in this TAG Security and Compliance meeting [recording](https://zoom.us/rec/play/xnVVuSXUnny9ujVxEpyZu45Wlr9AKzT-c-QHv2wO62ziFttPQ0fegU6eXa7lbySxAkxko4NtCg3AIsZ5.XRkHhI-CQiXpkKeo?eagerLoadZvaPages=sidemenu.billing.plan_management&accessLevel=meeting&canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fzoom.us%2Frec%2Fshare%2FiCVlHJ-4R7vw92e9SUF-DGkbpK4D1Gm3r6Acivil0rhZ0THKtkMphNNCnsEC35E.PHourL9HhYBcgljQ)
> docs: adds Automated Governance to Cloud Native Security Lexicon

- community/publications/supply-chain-security-tools/README.md
- community/publications/supply-chain-security-tools/securing-artifacts.md
- community/publications/supply-chain-security-tools/securing-build-pipelines.md
- community/publications/supply-chain-security-tools/securing-deployments.md
- community/publications/supply-chain-security-tools/securing-materials.md
- community/publications/supply-chain-security-tools/securing-source-code.md
Fixes https://github.com/cncf/toc/issues/1782
> Add call to action for community contribution of supply chain tool mappings
