roadmap.md

fixed #48
note this overview of our roadmap was included in the slides for [4/17 TOC meeting](https://docs.google.com/presentation/d/1QsBRsPU8E7AovvIGC-QIjxcfeQMcLd47iAzpoMFliII/edit#slide=id.g36fd28bfd4_5_8)

move roadmap from google doc to markdown

---

governance.md

small adjustment to wording, submitting as PR since it changes the meaning 
but I believe it is consistent with the rest of the document

lazy consensus applies to any proposal, not just candidates

---

README.md

We've been meeting every Friday, but the README says `every other Friday`. Please reject if my info is out-of-date - but if not, this seems like a good correction to make.

Update meeting frequency in README to every Friday

---

safe_usecases.md

addresses https://github.com/cn-security/safe/issues/32, I've annotated Quota Operator with a description based on comments by @ckemper67 in the issues
Sorry about the whitespace diffs... viewing the "rich diff" will show just the added text:
Since quota is often used for cost control, this may imply a different persona with financial, rather than an engineering background.
An important use of quota is to protect a service from abuse. By setting a quota, we can ensure that a single individual or group cannot bring down the service for everybody else (either intentionally or unintentionally). For example, services may lack sufficient protections (such as exponential backoff) and a simple quota enforcement in front of the service can reduce the impact of repeated request on the rest of the …

description of quota operator

---

README.md

just realized the CNCF Slack channel doesn't seem to be included

add slack channel info

---

README.md

no longer at Google, so leaving blank for now

removing Google affiliation

---

README.md
governance/README.md
governance/charter.md
governance/cncf-projects.md
governance/process.md
governance/roles.md
usecases.md

The CNCF TOC SIG process include approval of the [charter](https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md#sig-charter).
To facilitate that, this PR is refactors original charter from README 
into the governance folders. 
Then added:
* some from the [Worked Example](https://docs.google.com/document/d/18ufx6TjPavfZubwrpyMwz6KkU-YA_aHaHmBBQkplnr0/edit) which SAFE WG members drafted in collaboration with TOC members
* included scope from #23 
* Consistency for "end user" -- remove the dash, since it's a noun here (see below) -- prior version was inconsistent even within a single doc (usecases.md). The [CNCF Style Guide](https://github.com/cncf/foundation/blob/master/style-guide.md) doesn't have specific guidance but they use "end user" and for other things refer to [IEEE Style …

Charter => governance: add more details, scope, and CNCF SIG references

---

README.md
past-events.md

moving links to the conference talks into a PR, so that others can contribute content! 
related to: https://github.com/cncf/sig-security/issues/127

CloudNativeCon talks as repo content

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

first cut at contribution guide: https://github.com/cncf/sig-security/issues/180
added a code-of-conduct since it felt like CNCF version was mostly focused on code and wanted to expand on expectations for live, in-person interactions

contribution guide and code-of-conduct

---

.github/settings.yml
assessments/guide/security-reviewer.md
governance/roles.md

add details for 
- triage team (https://github.com/cncf/sig-security/issues/198)
- security assessment facilitator

document currently active roles

---

.github/settings.yml
assessments/guide/security-reviewer.md
governance/roles.md

Reverts cncf/sig-security#219
want to address comments before merge

Revert "document currently active roles"

---

assessments/projects/in-toto/self-assessment.md

Fixed a few mistakes, while reading the in-toto self-assessment, including
- typos/spelling
- full stops for consistency
- missing/wrong links
- excess whitespace
@SantiagoTorres, please note my change in [L382](https://github.com/cncf/sig-security/compare/master...lukpueh:fix_in-toto_assessment?expand=1#diff-39701274bea97973dc88cb502dfa9a77R382). You wrote "*artifact rules*", but I think you meant *"firewall rules"*, is this correct?
Thanks for the great write-up!

Fix mistakes in in-toto self-assessment

---

.github/ISSUE_TEMPLATE/security-assessment.md
assessments/guide/project-lead.md
assessments/guide/security-reviewer.md

To address https://github.com/cncf/sig-security/issues/156

Document security reviewer conflict of interest

---

.github/settings.yml

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

add Justin Cormack as a meeting facilitator

---

.github/ISSUE_TEMPLATE/presentation.md

Addressing https://github.com/cncf/sig-security/issues/264

Presentation template

---

README.md

"List of Meetings" is redundant in the "Meeting times" because
it duplicates the information in the "Additional Information" section.
Another thing is that when you click it, it doesn't lead you to
the right place.
Member list should be fixed too - it too doesn't lead you to the right
section on the README file.

Small tweaks on the README

---

assessments/intake-process.md

updated intake process per last tech lead/co-chair regarding CNCF/non-CNCF projects requesting review.  gives the area lead authority to kick them from the queue if the are lead determines they are no-longer communicating.

updated per #399, need @justincappos should definitely review

---

.github/ISSUE_TEMPLATE/security-assessment.md

/s/conflics/conflicts
Declaration of conflicts seem too often an omitted step that delays the start of assessments. Rephrasing with the hope reviewers pay attention at time of volunteering and that this step doesn't get skipped.

Typo and clarify declaration of conflict

---

supply-chain-security/README.md
supply-chain-security/compromises/compromise-definitions.md

Most notably this expands the definition of negligence and adds a definition of attack chaining, both suggested in #407. I've also added some notes on mitigating dev tooling attacks.

Minor edits for the supply chain compromise catalogue

---

assessments/projects/spiffe-spire/README.md

SPIFFE acronym stands for Secure Production Identity Framework for Everyone, see https://spiffe.io/

Update spiffe assessment to fix SPIFFE acronym

---

assessments/projects/spiffe-spire/self-assessment.md

These blog posts were moved from scytale.io to spiffe.io.

Update SPIFFE/SPIRE Security Assessment Blog Links

---

README.md

- adding Lewis Denham-Parry as a SIG member

docs: add new SIG member

---

README.md

Cleaned up and touched up appearance of the readme file:
* Enlarged SIG-Security logo to full-width
* Typos/punctuation
* Removed stale link
* Updated description of meeting timezone from USA centric to GMT offset
* Rephrased in-person meetups to gatherings and added upcoming EU event

README Housekeeping

---

README.md

As per discussion in the CNCF slack channel #sig-security [here](https://cloud-native.slack.com/archives/CDJ7MLT8S/p1611335962006600?thread_ts=1584742132.094800&cid=CDJ7MLT8S) a meeting time of 1pm AEDT every Tuesday has been decided for APAC meetings.
I'm unsure if the same google doc link would be valid so have left it as a 'globl' link for now. @TheFoxAtWork has confirmed the same Zoom are details to be used. I have done a little reformatting of the Zoom section.
First meeting currently to be Feb 2nd.

Add APAC meeting time

---

supply-chain-security/compromises/2020/thegreatsuspender.md

Update because of this article:
https://9to5google.com/2021/02/04/the-great-suspender-extension-has-been-removed-from-chrome-web-store-for-containing-malware/

Update: thegreatsuspender blocked on Chrome store

---

CONTRIBUTING.md
NEWMEMBERS.md
assessments/guide/outline.md
roadmap.md
security-whitepaper/cloud-native-security-whitepaper.md

Links to usecases are currently dead after the merge of #527 
This PR updates links to the new usecase-personas folder. I have chosen to not link directly to the README.md file to align with an idea that multiple usecases could exist in this folder over time.

Update links to usecases where currently broken

---

.github/settings.yml

we shouldn't use Github UI anymore because that is confusing

add comment to explain better how this works

---

CODEOWNERS

before they were just added to README, but we want them to be the whole repo as is reflected in the comment

add new TLs as repo CODEOWNERS

---

CODEOWNERS

Looks like @ultrasaurus 's change on https://github.com/cncf/sig-security/pull/541/files  altered the permissions
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners cites:
> Unless a later match takes precedence,
For which the previous /README.md had more restrictions and removes their merge access among others

Attempting correction to CODEOWNERS for new TLs

---

roadmap.md

Why:
* Important to link the Roadmap planning board and other regular business boards
* creating new tables with links to respective boards

What: Updated Roadmap with boards

---

roadmap.md

Why:
* The SIG has completed the activities described in the Discover section
* reflecting the status change through italics & marking the detailed list complete

What: Transition from Discover to Describe

---

.github/settings.yml

🔐CNCF Technical Advisory Group on Security (STAG) -> 🔐CNCF Security Technical Advisory Group (STAG)

Minor name update for consistency

---

supply-chain-security/supply-chain-security-paper/README.md

- Fixes a link to the markdown file in `supply-chain-security-paper/README.md`

Update SSCSP markdown link

---

supply-chain-security/supply-chain-security-paper/sscsp.md

Added version commit hash so that when the paper needs to be updated, changes can be easily diff'ed to create an errata for the original version

Add version commit hash for future diffing

---

.github/settings.yml

Add @magnologan as a meeting facilitator
- Frequent member of Security TAG meetings since October 2020
- Helped organized the Cloud Native Security Day CTF in 2020 and 2021.
- Server as a facilitator for this meeting once
- Member of the Toastmasters International

Add meeting facilitator

---

governance/charter.md

Only remaining SIG reference is for k8s SIGs which are still SIGs

SIG => TAG governance/charter

---

CODE-OF-CONDUCT.md

reviewing diffs is easier if text is wrapped at 80 columns 
if this looks good, then ideally it would be merged before https://github.com/cncf/tag-security/pull/652

wrap at 80 columns, trim trailing whitespace

---

CODE-OF-CONDUCT.md

small changes to make repeat references easier in https://github.com/cncf/tag-security/pull/652

shortlinks to help with wordwrap and (future) repeat references

---

.github/settings.yml

This is an informational non-impacting update of meeting facilitators.

Add chasemp (Chase Pettet) to meeting facilitators

---

governance/process.md

in talking about triage last week, how the different templates are used wasn't clear,
so I thought I would document how we had originally set that up

add detail about how different github issue templates are used

---

README.md

part of https://github.com/cncf/tag-security/issues/655

add leadership lists, rename group email list sig-to-tag

---

ci/spelling.sh

Example of how it worked before and works now:
```shell
$ echo -e "test1.md\ntest2.xmd\ntest3.md.gz" | grep .md
test1.md
test2.xmd
test3.md.gz
$ echo -e "test1.md\ntest2.xmd\ntest3.md.gz" | grep '\.md$'
test1.md
```
See for details: https://github.com/cncf/tag-security/pull/706#discussion_r660478220

Improve the regexp for handling .md files

---

ci/spelling-config.json

via @JohnHillegass 
> So I think where this is messing up is we excluded that whole .github dir from cspell execution but grep is seeing markdown files changed there and passing forward to xargs. Since the first arg is not empty xargs is taking it and passing to cspell. Cspell since its been told to skip that path, returns a non-zero code and xargs throws the 123. Changing like above handles this case. To fix we will need to change ignorePaths "**/.github/**" to "**/.github/workflows/**" in the ci/spelling-config.json

fix spellcheck error in 609-proposal-project branch

---

README.md

- Use "today" as a date, rather than a given date (should keep working even after DST changes)
- Show conversion only for the time we our interested in (the meeting) rather than every hour of the day
Note : for the APAC meeting, AEDT (Australia Eastern Daylight Time) is not currently observed, as East Australia is currently on AEST. Not sure what the best option is here, maybe clarify if we settle on Sydney time, for instance?
Also, change GMT to UTC, which is technically more correct (for what that matters…)

README: Update timezone links to more helpful ones

---

governance/related-groups/README.md

The above name of the group might change as the groups just
started and things like name, governance, etc. might change over
time. Will update if/when it does.

Add SLSA Maintainers to related groups

---

governance/related-groups/README.md

Just basic editing to make the bullets points consistent.
Also, moved the list of cSpell ignored words (ie: usernames) to the top, as putting a `` line  in the middle of a bullet list resets Github's rendering of the list, breaking the desired bullet depth.

Clean up related groups for readability

---

governance/roles.md
governance/tech-lead-proposal-process.md

Why:
* co-chair process is documented, TL's also should be
* introduces a community driven option

What: Document proposed tech lead nomination process

---

CONTRIBUTING/first-time-contributions.md

I think the "Members section in `README.md`", which means the `README.md` file in the root.

Fix link in contribution guide

---

README.md
cloud_native_security.md
past-events.md

Also moved prior CN security days to the cloud_native_security.md from
past-events.md, and linked to that doc so things are in one place.

Updating kubecon event in readme

---

governance/paper-process.md

During initial Cloud Native Security Whitepaper, it was discussed how the attribution and authorship should be carried out for papers produced by the STAG.

Add Contributors process for papers

---

supply-chain-security/compromises/2021/coa-rc.md
supply-chain-security/compromises/2021/klow-klown-okhsa.md
supply-chain-security/compromises/2021/ua-parser-js.md
supply-chain-security/compromises/README.md

I'm a little unclear which compromise-definition applies to the klow/klown/okhsa situation, since they seem to have been new packages. I've added them separately because of the connection to ua-parser-js.

Add klow / klown / okhsa, ua-parser-js, coa, rc breaches

---

governance/tech-lead-transition.md

Why:
* Address issue TL Transition Checklist #847 in order to provide continuity and consistency
* Documenting the checklist created from issue TL Transition Checklist #847 for reuse.

What: Create TL Transition checklist (#847)

---

supply-chain-security/compromises/2022/js-faker-colors.md
supply-chain-security/compromises/2022/node-ipc-peacenotwar.md
supply-chain-security/compromises/README.md

Adds node-ipc/peacenotwar compromise
This post is strongly based on the existing `2022/js-faker-colors.md`
I'm looking for guidance around the amount of users affected. NPM downloads was stopped just short of 43k downloads. I've just changed it to "medium" for now.
Also there's the limiting factor of the rewriting only being for specific IPs but AFAIK the text file is always written to desktop
I'll keep this draft for a bit to get input and since it's a very recent event

compromises: 2022 - node-ipc

---

security-whitepaper/README.md

I believe it should be "Posted PDF second version", not "Posted PDF first version"?

Update README - Fix PDF v2 wording

---

.github/workflows/sig-sec-check.yml

Explicitly set a supported Node.js version which some tooling on this workflow requires.
In fact, CI currently fails on the `Spelling` step due to defaulting to Node.js 12, yet requiring Node.js 14 ([see here](https://github.com/cncf/tag-security/runs/6649092902?check_suite_focus=true)), such as:
```
+ cspell@6.0.0
added 150 packages from 65 contributors in 8.822s
From https://github.com/cncf/tag-security
* [new branch]      main       -> main
* [new branch]      main       -> origin/main
ApplicationError: Unsupported NodeJS version (12.22.12); >=14 is required
```

build: use Node.js LTS for tooling

---

supply-chain-security/compromises/compromise-definitions.md

Updating the table of contents to include the new `Malicious Maintainer` type of compromise.

docs: update table of contents

---

assessments/guide/joint-review.md

Signed-off-by: Andrew Martin <sublimino@gmail.com>

docs: add warning about invalid markdown due to linter

---

README.md
cloud_native_security.md
past-events.md

The README.md file contains a list of upcoming events, and it's quite out of date. It currently shows KubeCon Europe as happening in the future and doesn't list KubeCon 2022 (which is basically over) or SecurityCon 2023. This PR updates this to list only SecurityCon 2023 since that's the only one that's currently in the future. It also adds KubeCon EU and NA 2022 to the list of past events and updates the language around Cloud Native SecurityCon.
Fixes #998

Add SecurityCon 2023 to README

---

CONTRIBUTING/first-time-contributions.md
ci/link-config.json
ci/spelling.sh

Provide suggested fix for cSpell errors. Resolves #724. Thank you to @ultrasaurus for the help text which I only modified slightly.
Note: #1001 should be merged before this.
Example output when adding a fake word to a markdown file and running `make spelling`:
```
1/1 ./CONTRIBUTING/README.md 588.82ms X
/usr/src/app/CONTRIBUTING/README.md:9:1 - Unknown word (testsett) Suggestions: [testnets, testnet, testiest, tested, testee]
CSpell: Files checked: 1, Issues found: 1 in 1 files
Spelling errors detected in markdown files (see above output for details).
If the errors are names, external links, or unusual but accurate technical words,
then you should create an inline comment like:
Of course, you should only include non-dictionary words that are correctly spelled!
If the error happens because …
```

Cspell suggestions

---

ci/spelling-config.json
governance/charter.md

Updates to the current version of `governance/charter.md` to resolve spelling and linting issues identified but not part of [PR 118](https://github.com/cncf/tag-security/pull/1018) as discussed in the TAG Security meeting today.

Resolving spelling/linting in governance/charter.md

---

governance/github.md

- Adds a section to the github.md governance document for handling of PRs where the submitter has not been responsive to fixing requested changes.
- Also improves the grammar and language of the section that deals with branching.
See discussion in Slack (#tag-security channel). CC @TheFoxAtWork 

Add guidance for PR collaboration

---

website/content/blog/security-village-eu-2023.md

Add a post about the security village with a link to the unconference signup.
This page will be used during the event to list the unconference schedule.

Add initial post about security village

---

supply-chain-security/compromises/2021/repojacking.md
supply-chain-security/compromises/README.md

I was going through the catalog of supply chain compromises, and noticed that a novel (to me) publication from 2021 wasn't included.

Add repojacking example from 2021.

---

security-whitepaper/v2/cloud-native-security-whitepaper.md

A citations of 5 existed in v1, but the number was removed due to a revise of v2. Also this PR fixed a citations format. 
Since Citations of markdown appear at the end, it might be better to bring Acknowledgements to the front or delete headlines of Citations.

Fix some issues in citations

---

README.md

- this change moves the Zoom link to the group's room
- the group's room supports auto-streaming to YouTube
I've updated the two meeting Calendar Invites on CNCF TAG-Security Public Calendar to reflect this change.

fix: update Zoom link

---

README.md

LF guidance is to internationalize the schedule by displaying meeting times in UTC and to decouple from centralizing to the local timezone of a particular location. 
* Replaces London for UTC+0 and UTC+1 to account for the difference in daylight savings during summer months.
* Replaced time.is link from what time is in London to what time is UTC.

i18n EMEA meeting time from London to UTC

---

CODEOWNERS
provenance-implementation/README.md
provenance-implementation/argo/argo-cd.md

This is based on the proposal made by the TAG Security community to house provenance ingestion documentation for projects, following the approach that was requested by @mlieberman85 and @mnm678.
I've created a subdirectory with instructions and a single example (Argo CD).

Added provenance-implementation hub w/ README and example

---

README.md

Copies the new words on TAG webpage on meeting times. This is for repo and page to be consistent. 
This also consolidates meeting info, calendar, and zoom details in less words than what we had before.

Update README.md with web page meet details

---

assessments/projects/flatcar/joint-assessment.md

adding flatcar joint assessment doc

adding Flatcar joint-assessment to security review 

---

ci/links.sh
ci/lint.sh
ci/setup.sh
ci/spelling.sh

Linting scripts were failing to Git safe dirertory check, both when run via GH actions, or locally via docker-compose. To fix the scripts, few things need to be changed.
1. Add /usr/src/app to Git safe directories, so Git will run any Git commands, such as "git fetch ..." in that directory.
2. Add "set -e" so command failure will fail the script, to produce correct return code for the check.
3. Due "set -e", and the loop we are running, we need to ignore the linting command returning failure, and capture the failure to be returned later command.
4. We also need to remove the grep from the pipeline. If the commit has no matching files, it would return false error, thanks to "-o pipefail". Same can be applied to all scripts, having Git filter the wanted files, instead of having additional …

ci: fix ci linter scripts

---

assessments/projects/jaeger/actions.md
assessments/projects/jaeger/self-assessment.md

I have updated the self-assesment to remove the "pending changes" part of the text and thank the Security Pals folks for the contribution to the project!
I have removed the actions.md file as well since the issue flagged there was corrected in July 2023 per [this Github advisory](https://github.com/jaegertracing/jaeger/security/advisories/GHSA-2w8w-qhg4-f78j).

Remove actions and update self-assesment

---

supply-chain-security/compromises/2003/kernel-repository.md
supply-chain-security/compromises/2010/fsf-website.md
supply-chain-security/compromises/2012/ruby-on-rails-github.md
supply-chain-security/compromises/2021/php.md
supply-chain-security/compromises/2022/auth0-source-code-leak.md
supply-chain-security/compromises/2022/okta-github-repo-leak.md
supply-chain-security/compromises/2023/fake-dependabot.md
supply-chain-security/compromises/README.md

This PR adds various incidents to the supply chain compromises catalog:
- Okta GitHub repo hack
- Auth0 source code theft
- Linux kernel CVS repo hack
- Ruby on Rails / GitHub vulnerability exploited by security researcher
- FSF website hack
- Fake dependabot commits
In addition, it fixes tags on the PHP Git server incident.

Add various supply chain incidents to the catalog

---

README.md
governance/README.md
website/Makefile
website/content/_index.md

Closes #1244 
Much more to do on the website - but this resolves a majority of the broken links identified in the linked issue. 
I don't see support for utilization of a `root/` content directory in conjunction with the standard `content/` directory for the website. 
Copy required files to the `website/content` directory in order to support resolving links from the homepage to other markdown files within the repository. 
Would be good to standardize the repository with what we intended to expose via the website. Rsync command was re-worked to essentially deny everything by default unless allowed.

fix(links): shift file transfer to content directory

---

README.md

adds @jkjell  
adds three tables to the README to better organize the list of Security TAG members

Add John Kjell to TLs

---

publications/README.md

This PR organizes the contents of the TAG Security publications into a structured table format for easier reference and access. Each publication is categorized and linked, improving the readability and usability of the documentation.
- Added a table listing all the publications and resources produced by TAG Security.
- Included descriptions, formats, and links for each publication.
The previous format was less structured, making it difficult to quickly locate specific publications and resources. By organizing the content into tables, we enhance the user experience and facilitate easier navigation. This will also make it easier to pull to the site.

chore: Organize TAG Security publications into table format

---

assessments/projects/cert-manager/self-assessment.md

A reviewer spotted a couple of minor things with the cert-manager self assessment after it was merged.
This PR fixes those, and slightly rewords the "Self-assessment Use" section.

fix minor typos / formatting issues in cert-manager self-assessment

---

supply-chain-security/compromises/2010/apache.md
supply-chain-security/compromises/2010/fsf-website.md
supply-chain-security/compromises/2010/proftpd.md
supply-chain-security/compromises/2011/kernelorg.md
supply-chain-security/compromises/2013/apt.md
supply-chain-security/compromises/README.md

This is first in a (expected) series of PRs to update the supply chain compromises catalog. 
- Fix link in index
- Update incident title to make it verbose
- Add note to review incidents that are possibly outside the scope of SSC security

docs: Update SSC compromise catalog

---

website/netlify.toml
website/package-lock.json
website/package.json

This PR attempts to bump the Hugo version used by netlify when building the website from 0.115.2 (released in [July 2023](https://github.com/gohugoio/hugo/releases/tag/v0.115.2)) to 0.128.0, the [latest stable release at this time](https://github.com/gohugoio/hugo/releases/tag/v0.128.0). 
The PR also bumps the hugo-extended npm package version to latest stable: https://www.npmjs.com/package/hugo-extended/v/0.127.0

Upgrade website netlify hugo version

---

ci/spelling-config.json
website/content/blog/website-relaunch-2024.md

It would be nice to have a recent post on the blog when we announce the website revamp in the CNSC keynotes.
This won't show on the preview or website until after the release time passes.

Added website relaunch blog

---

website/layouts/_default/baseof.html

Commenting the line for the construction banner. Allows for use later if required.

Remove construction banner from website

---

website/themes/docsy/assets/scss/_table.scss
website/themes/docsy/assets/scss/main.scss

This SCSS fix addresses the following action item in https://github.com/cncf/tag-security/issues/1257
> The publications table is too wide— in the final column "Link" four letters is getting broken up into two lines.

Fix website publications table link column

---

governance/roles.md

As per [this comment](https://github.com/cncf/tag-security/issues/398#issuecomment-2206903201), the roles.md document still says that all members are listed in the repository, which is no longer true. This PR removes this outdated language.

Remove outdated info about documenting members

---

website/themes/docsy/assets/scss/_logo.scss
website/themes/docsy/assets/scss/main.scss

The default styling for the TAG-Security logo on the website homepage does not constrain its size so it may be very large depending on the screen size.
This PR addresses this style issue by enforcing a max size of 500px regardless of the size of the screen by using a specific SCSS selector for the logo image.

Specify max size for TAG-Security logo on website homepage

---

.github/workflows/sig-sec-check.yml
Makefile
community/automated-governance/README.md
docker-compose.yml

Noticed failures with CI processes in Pull Requests. Noticed that our use of `ubuntu-latest` may have resulted in these issues after the [removal](https://github.com/actions/runner-images/commit/2a4bc14da46f1f8e358aa902a69edb9bef135472) of docker compose v1. 
- Update `Makefile` to use docker compose v2 syntax
- Remove obsolete `version` in `docker-compose.yml`
- Update the `TAG-Security-Linter` to use the latest version of `actions/checkout` pinned to the commit SHA to remove deprecation warnings with the use of older `node` actions.

fix(ci): update Makefile to docker compose v2

---

README.md

This PR updates the leadership for the Automated Governance Working Group. Due to other commitments, I will be stepping down as the lead for this group. @matthewflannery who has been a co-lead from the start, has graciously stepped up to take on the lead role along @brandtkeller.

Update Lead for AG Working Group

---

.github/auto_request_review.yml
README.md
community/resources/security-whitepaper/secure-defaults-cloud-native-8.md

Remove personal references (Andres Vega and @anvega) from README.md, and auto_request_review.yml to complete https://github.com/cncf/tag-security/issues/1349.

Remove personal references (Andres Vega and @anvega) from project files and documentation

---

README.md

CI "Links" stage fails because of some broken links in the README file.

fix(README): broken links

---

README.md

Bi-Weekly EMEA meeting has moved to LFX, and the README should reflect the new meeting link.

docs(README): update EMEA meeting zoom link

---

website/layouts/partials/head.html

As part of the LF push to advertise events more broadly, this deploys the "hello" bar seen at the top of the CNCF site. It will be deployed to all CNCF subsites as per [this issue](https://github.com/cncf/cncf.io/issues/598). It takes its settings from the main CNCF site and will appear only when the CNCF site has it active.

Adds CNCF "hello" bar above topnav

---

README.md

The Members heading in the past documented all contributing members. This has since been removed due to the sheer growth of contributors, and has been left in the README as an empty placeholder.
Thus, the "## Members" heading is redundant.

Update README.md to remove Members heading

---

community/assessments/projects/lima/self-assessment.md

Add self-assessment of [Lima](https://lima-vm.io) (CNCF Sandbox)
cc @jandubois @afbjorklund @balajiv113

self-assessment: add Lima

---

ci/links.sh

Fixes #1402 
Pins the use of `markdown-link-check` to `3.12.2` following a regression in the latest releases which breaks with the use of config files. 
Tested locally with desired results.

fix(lint): pin markdown-lint-link to known good version

---

community/assessments/projects/open-telemetry/self-assessment.md

As part of our graduation efforts (see https://github.com/cncf/toc/pull/1271), OpenTelemetry is submitting an updated security self-assessment for review.

Update OpenTelemetry Security Self-Assessment

---

community/assessments/projects/openebs/self-assessment.md

This is the initial self-assessment for OpenEBS.

Add OpenEBS self-assessment

---

community/resources/security-fuzzing-handbook/fuzzing-handbook.md
community/resources/security-whitepaper/README.md

The fuzzing-handbook.md had some information on the top of the page that was broken on the website. This PR removes it.
The security whitepaper README.md had a reference to an emoji, that did not render on the website only showing its code. This PR also removes it.

Corrections on fuzzing-handbook.md and security whitepaper README.md

---

community/catalog/compromises/queue.yaml

Sometimes security researchers and the media will discuss an incident and describe it as a supply chain attack. This is starting to happen faster than we can review them and evaluate how they fit the criteria for adding them to the catalog. The goal of this queue is to keep track of the cases. It also helps current and future contributors by giving them good first tasks. If someone reads the incident descriptions and determines it doesn't meet the criteria, they can delete the entry. Alternatively, if they write a short page about it, they can delete the entry when they make their PR. I'm looking forward to hear what others in the community think about this.

Proposing a queue for cases in the community compromises catalog

---

community/publications/README.md

[Link check action](https://github.com/cncf/tag-security/actions/runs/13972278904/job/39116973585) is failing because the controls WG got moved to archive.

Fix a link check failure

---

website/Makefile

After having some issues setting up the environment locally on MacOS, we figured it out what the problem was.
This PR adapts the Makefile script to work correctly when setting up the environment for local development.
Thanks Brandt and Eddie for the help on this issue!

Updating the Makefile script on the website to work natively with MacOS.

---

community/resources/security-whitepaper/v2/cloud-native-security-whitepaper.md

The GitHub link to the `main` branch doesn't work.

Link to rendered security lexicon website

---

README.md

Updating meeting links in our repo and the website. This will likely be overwritten by future website changes, but should help folks find the meeting for now.

Update meeting links

---

.github/ISSUE_TEMPLATE/joint-review.md

Update the `joint-revew` template to reflect the new location

chore: update joint review template with redirection to toc repo

---

community/working-groups/supply-chain-security/supply-chain-security-paper/sscsp.md

This PR fixes #1357 by updating the broken /supply-chain-security/compromises link.
The link now points to the correct location:
https://github.com/cncf/tag-security/tree/main/community/catalog/compromises

fix(docs): correct broken link to compromises catalog (#1357)
